version: "3.8"
services:
  spent-tracker:
    build: .
    container_name: spent-tracker
    ports:
      - "8067:8067"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=production
    volumes:
      - .//app/data
    restart: unless-stopped
