version: "3.9"

services:
  spend:
    build: .
    container_name: spend
    ports:
      - "8067:8000"
    volumes:
      - ./expenses.db:/app/expenses.db
      - ./static/charts:/app/static/charts
    restart: unless-stopped
