version: "3.9"

services:
  spent:
    container_name: spent
    build: .
    ports:
      - "8067:8067"
    volumes:
      - ./data:/app/data # DB persists automatically
      - ./templates:/app/templates
      - ./static/charts:/app/static/charts
    restart: unless-stopped
